# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XN1ts1PkSIYbm9d66HJYcoIIiSnk4K6k
"""

import pandas as pd
import matplotlib.pyplot as plt
data={
    "STUDENTS":["S1","S2","S3","S4","S5","S6","S7","S8","S9","S10"],
    "STUDY_HOURS":[2,3,4,5,7,8,9,6,8,9],
    "ATTENDANCE":[65,70,75,80,85,90,75,65,80,90],
    "ASSIGNMENT_MARKS":[14,15,16,17,18,19,17,18,15,16],
    "INTERNAL_MARKS":[18,22,20,24,21,25,28,29,24,21],
    "FINAL_MARKS":[45,50,55,60,65,70,85,55,75,80]
}
df=pd.DataFrame(data)
print(df)

plt.hist(df["FINAL_MARKS"],bins=5)
plt.xlabel("FINAL MARKS")
plt.ylabel("NO OF STUDENTS")
plt.title("Distribution of Final Marks")
plt.show()

plt.boxplot(df["FINAL_MARKS"])
plt.xlabel("FINAL MARKS")
plt.title("Boxplot of Final Marks")
plt.show()
#

plt.boxplot([
    df["STUDY_HOURS"],
    df["ATTENDANCE"],
    df["ASSIGNMENT_MARKS"],
    df["INTERNAL_MARKS"],
    df["FINAL_MARKS"]
])
plt.xticks([1,2,3,4,5],["Study Hours","Attendance","Assignment Marks","Internal Marks","Final Marks"])
plt.ylabel("VALUES")
plt.title("Box plot of Student Performance")
plt.title("Boxplot of Subjects")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
data={
    "STUDENTS":["S1","S2","S3","S4","S5","S6","S7","S8","S9","S10"],
    "STUDY_HOURS":[2,3,4,5,7,8,9,6,8,9],
    "ATTENDANCE":[65,70,75,80,85,90,75,65,80,90],
    "ASSIGNMENT_MARKS":[14,15,16,17,18,19,17,18,15,16],
    "INTERNAL_MARKS":[18,22,20,24,21,25,28,29,24,21],
    "FINAL_MARKS":[45,50,55,60,65,70,85,55,75,80]
}
df=pd.DataFrame(data)
print(df)

import seaborn as sns
import matplotlib.pyplot as plt

sns.pairplot(
    df[
        [
            "STUDY_HOURS",
            "ATTENDANCE",
            "ASSIGNMENT_MARKS",
            "INTERNAL_MARKS",
            "FINAL_MARKS"
        ]
    ]
)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
sns.heatmap(df.corr(numeric_only=True),annot=True)
plt.title("Corelation Heatmap")
plt.show()

plt.scatter(df["STUDY_HOURS"],df["FINAL_MARKS"])
plt.xlabel("STUDY HOURS")
plt.ylabel("FINAL MARKS")
plt.title("STUDY HOURS VS FINAL MARKS")
plt.show()
#